# Generated by Django 6.1.1 on 2026-09-30 11:28

import django.core.validators
from django.db import migrations, models

import pullini.projects.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "repo_url",
                    models.CharField(
                        max_length=500, validators=[pullini.projects.models.validate_git_url]
                    ),
                ),
                ("branch", models.CharField(default="main", max_length=200)),
                (
                    "docs_folder",
                    models.CharField(
                        default="docs",
                        help_text="Path within the repository that contains the documentation.",
                        max_length=200,
                    ),
                ),
                (
                    "update_interval_minutes",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="How often to synchronize from Git, in minutes.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
