# Generated by Django 6.1.1 on 2026-09-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_projectsyncstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("url_path", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField(help_text="Source Markdown.")),
                ("html", models.TextField(help_text="Rendered HTML.")),
                (
                    "plain_text",
                    models.TextField(help_text="Tag-stripped text, indexed by search (E5)."),
                ),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "indexes": [
                    models.Index(
                        fields=["project", "url_path"], name="wiki_page_project_9a8c12_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "path"), name="unique_page_path_per_project"
                    )
                ],
            },
        ),
    ]
