apiVersion: v1
kind: Service
metadata:
  name: pullini
  namespace: pullini
  labels:
    app.kubernetes.io/name: pullini
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pullini
  ports:
    - name: http
      port: 80
      targetPort: http
