import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const wikiDir = resolve(scriptDir, '..', 'wiki')
const pagesDir = join(wikiDir, 'pages')

const GROUP_ORDER = ['Overview', 'Epics', 'Specs', 'Plans', 'Tickets', 'Research']
const ROOT_RANK = { 'project-overview.md': 0, 'build-deploy.md': 1, 'debugging.md': 2 }

function toPosix(path) {
	return path.split(sep).join('/')
}

function stripQuotes(value) {
	const trimmed = value.trim()
	if (
		(trimmed.startsWith('"') && trimmed.endsWith('"')) ||
		(trimmed.startsWith("'") && trimmed.endsWith("'"))
	) {
		return trimmed.slice(1, -1)
	}
	return trimmed
}

function walk(dir, out = []) {
	if (!existsSync(dir)) {
		return out
	}
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name)
		if (entry.isDirectory()) {
			walk(full, out)
		} else if (entry.name.endsWith('.md')) {
			out.push(full)
		}
	}
	return out
}

function parseFrontmatter(text) {
	const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/)
	const data = {}
	if (!match) {
		return { data, body: text }
	}
	let key = null
	for (const rawLine of match[1].split(/\r?\n/)) {
		const line = rawLine.replace(/\s+$/, '')
		const item = line.match(/^\s+-\s+(.*)$/)
		if (item && key) {
			if (!Array.isArray(data[key])) {
				data[key] = []
			}
			data[key].push(stripQuotes(item[1]))
			continue
		}
		const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/)
		if (kv) {
			key = kv[1]
			const value = kv[2].trim()
			data[key] = value === '' ? [] : stripQuotes(value)
		}
	}
	return { data, body: text.slice(match[0].length) }
}

function titleOf(body) {
	const match = body.match(/^\s*#\s+(.+)$/m)
	return match ? match[1].trim() : ''
}

function groupOf(relPath) {
	const parts = relPath.split('/')
	const sub = parts.length >= 3 ? parts[1] : null
	if (!sub) {
		return 'Overview'
	}
	const map = {
		epics: 'Epics',
		specs: 'Specs',
		plans: 'Plans',
		tickets: 'Tickets',
		research: 'Research',
	}
	return map[sub] || sub.charAt(0).toUpperCase() + sub.slice(1)
}

function collectPages() {
	return walk(pagesDir).map((full) => {
		const rel = toPosix(relative(wikiDir, full))
		const text = readFileSync(full, 'utf8')
		const { data, body } = parseFrontmatter(text)
		return { full, rel, data, body, title: titleOf(body) }
	})
}

function loadLegacySummaries() {
	const summaries = new Map()
	const indexPath = join(wikiDir, 'index.md')
	if (!existsSync(indexPath)) {
		return summaries
	}
	for (const line of readFileSync(indexPath, 'utf8').split(/\r?\n/)) {
		const match = line.match(/^\s*-\s*\[[^\]]*\]\(([^)]+)\)\s*(?:—|-)\s*(.*)$/)
		if (match) {
			const summary = match[2]
				.replace(/\.\s*Created\s+\d{4}-\d{2}-\d{2}\.?\s*$/, '')
				.trim()
			summaries.set(match[1], summary)
		}
	}
	return summaries
}

function rank(page) {
	const base = page.rel.split('/').pop()
	return ROOT_RANK[base] ?? 50
}

function buildIndex() {
	const legacy = loadLegacySummaries()
	const pages = collectPages()
	const groups = new Map()

	for (const page of pages) {
		const group = groupOf(page.rel)
		const summary = page.data.summary || legacy.get(page.rel) || page.title || ''
		if (!groups.has(group)) {
			groups.set(group, [])
		}
		groups.get(group).push({ page, summary })
	}

	const names = [...groups.keys()].sort((a, b) => {
		const ia = GROUP_ORDER.indexOf(a)
		const ib = GROUP_ORDER.indexOf(b)
		if (ia !== -1 || ib !== -1) {
			return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib)
		}
		return a.localeCompare(b)
	})

	const lines = [
		'# Wiki Index',
		'',
		'> Generated by `node scripts/wiki.mjs index` — do not edit by hand.',
		'',
	]
	for (const name of names) {
		lines.push(`## ${name}`)
		const items = groups
			.get(name)
			.sort((a, b) => rank(a.page) - rank(b.page) || a.page.rel.localeCompare(b.page.rel))
		for (const { page, summary } of items) {
			const label = page.rel.replace(/^pages\//, '').replace(/\.md$/, '')
			lines.push(`- [${label}](${page.rel})${summary ? ` — ${summary}` : ''}`)
		}
		lines.push('')
	}

	writeFileSync(join(wikiDir, 'index.md'), lines.join('\n'), 'utf8')
	console.log(`index.md updated (${pages.length} page(s))`)
}

function today() {
	return new Date().toISOString().slice(0, 10)
}

function appendLine(file, line, header) {
	if (!existsSync(file) && header) {
		writeFileSync(file, header, 'utf8')
	}
	const existing = existsSync(file) ? readFileSync(file, 'utf8') : ''
	const content = existing && !existing.endsWith('\n') ? `${existing}\n` : existing
	writeFileSync(file, `${content}${line}\n`, 'utf8')
}

function addLog(args) {
	const [action, ...rest] = args
	if (!action || rest.length === 0) {
		throw new Error('usage: wiki.mjs log <action> "<description>"')
	}
	appendLine(join(wikiDir, 'log.md'), `## [${today()}] ${action} | ${rest.join(' ')}`)
	console.log('log.md updated')
}

function addDecision(args) {
	const text = args.join(' ').trim()
	if (!text) {
		throw new Error('usage: wiki.mjs decision "<decision> — because <reason>"')
	}
	const file = join(wikiDir, 'decisions.md')
	let next = 1
	if (existsSync(file)) {
		const numbers = [...readFileSync(file, 'utf8').matchAll(/D-(\d+)/g)].map((m) => Number(m[1]))
		next = numbers.length ? Math.max(...numbers) + 1 : 1
	}
	const id = `D-${String(next).padStart(2, '0')}`
	const header =
		'# Decisions\n\nAppend-only decision record. The "why" lives here; the full change history lives in git.\n\n'
	appendLine(file, `- [${today()}] ${id} — ${text}`, header)
	console.log(`decisions.md updated (${id})`)
}

function lint() {
	const pages = collectPages()
	const indexPath = join(wikiDir, 'index.md')
	const indexText = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : ''
	const problems = []

	for (const page of pages) {
		if (!page.data.created) {
			problems.push(`${page.rel}: missing frontmatter "created"`)
		}
		if (!page.data.type) {
			problems.push(`${page.rel}: missing frontmatter "type"`)
		}
		const linkRe = /\]\((?!([a-z][a-z0-9+.-]*:|#))([^)]+\.md)(#[^)]*)?\)/g
		for (const match of page.body.matchAll(linkRe)) {
			const target = resolve(dirname(page.full), decodeURIComponent(match[2]))
			if (!existsSync(target)) {
				problems.push(`${page.rel}: dangling link -> ${match[2]}`)
			}
		}
		if (indexText && !indexText.includes(`(${page.rel})`)) {
			problems.push(`${page.rel}: not listed in index.md (run: node scripts/wiki.mjs index)`)
		}
	}

	if (problems.length === 0) {
		console.log(`lint OK (${pages.length} page(s))`)
		return
	}
	console.log(problems.join('\n'))
	process.exitCode = 1
}

const [command, ...args] = process.argv.slice(2)

try {
	switch (command) {
		case 'index':
			buildIndex()
			break
		case 'log':
			addLog(args)
			break
		case 'decision':
			addDecision(args)
			break
		case 'lint':
			lint()
			break
		default:
			console.log('usage: wiki.mjs <index|log|decision|lint> [args]')
			process.exitCode = 1
	}
} catch (error) {
	console.error(error.message)
	process.exitCode = 1
}
